# Generated by Django 5.0.4 on 2024-05-08 06:59

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=50)),
                ('country_code', models.IntegerField()),
                ('curr_symbol', models.CharField(max_length=15)),
                ('phone_code', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('my_user', models.ForeignKey(default='test1@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='app2.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=50)),
                ('state_code', models.IntegerField()),
                ('gst_code', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('country_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='app2.country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=50)),
                ('city_code', models.IntegerField()),
                ('phone_code', models.IntegerField()),
                ('population', models.BigIntegerField()),
                ('avg_age', models.IntegerField()),
                ('num_of_adult_males', models.BigIntegerField()),
                ('num_of_adult_females', models.BigIntegerField()),
                ('created_at', models.DateTimeField(default=datetime.datetime)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('state_id', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='app2.state')),
            ],
        ),
    ]
