# Generated by Django 5.0.4 on 2024-05-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_customuser_created_at_customuser_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
