# Generated by Django 5.0.4 on 2024-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='phone_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='curr_symbol',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='gst_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.IntegerField(unique=True),
        ),
    ]
