# Generated by Django 5.0.4 on 2024-05-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('city_code', models.IntegerField()),
                ('phone_code', models.TextField()),
                ('population', models.BigIntegerField()),
                ('avg_age', models.IntegerField()),
                ('num_of_adult_males', models.BigIntegerField()),
                ('num_of_adult_females', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('country_code', models.IntegerField()),
                ('curr_symbol', models.TextField()),
                ('phone_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('state_code', models.IntegerField()),
                ('gst_code', models.TextField()),
                ('phone_code', models.IntegerField()),
            ],
        ),
    ]
